# Generated by Django 3.0.3 on 2020-04-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='True', max_length=200),
        ),
    ]
